version: "3.7"
services:
  postgresql:
    container_name: postgres
    image: postgres:9
    environment:
      - POSTGRES_USER=digdag
      - POSTGRES_PASSWORD=digdag
      - POSTGRES_DB=digdag

  digdag:
    container_name: digdag
    build:
      context: .
    command: ["/usr/local/bin/digdag", "server", "--disable-executor-loop", "--disable-local-agent", "--config", "/etc/digdag/server.properties", "--task-log", "/var/log/digdag", "--access-log", "/var/log/digdag/access"]
    depends_on:
      - postgresql
    ports:
      - "65432:65432"
      - "65433:65433"
    volumes:
      - ./workflows:/workflows
      - logdata:/var/log/digdag

  worker1:
    container_name: worker1
    build:
      context: .
    command: ["/usr/local/bin/digdag", "server", "--config", "/etc/digdag/server.properties", "--task-log", "/var/log/digdag"]
    depends_on:
      - postgresql
    volumes:
      - ./workflows:/workflows
      - logdata:/var/log/digdag

  worker2:
    container_name: worker2
    build:
      context: .
    command: ["/usr/local/bin/digdag", "server", "--config", "/etc/digdag/server.properties", "--task-log", "/var/log/digdag"]
    depends_on:
      - postgresql
    volumes:
      - ./workflows:/workflows
      - logdata:/var/log/digdag

volumes:
  logdata:
